name: Update Resume PDF

on:
  repository_dispatch:
    types: [pdf_update]

jobs:
  update_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Download PDF
        run: |
          curl -o resume.pdf https://raw.githubusercontent.com/gavintranquilino/gavins-resume/main/out/Gavin_Tranquilino.pdf
          ls -la

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"          
          git add -A
          git commit -m "Update resume.pdf"
          git push
