name: Update Resume PDF

on:
  repository_dispatch:
    types: [pdf_update]

jobs:
  update_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Download PDF
        run: |
          curl -o latest.pdf https://raw.githubusercontent.com/gavintranquilino/gavins-resume/main/out/Gavin_Tranquilino.pdf

      - name: Copy PDF to Website
        run: |
          cp latest.pdf Gavin_Tranquilino.pdf

      - name: Commit changes
        run: |
          git clone https://github.com/gavintranquilino/gavintranquilino.github.io.git/
          cd gavintranquilino.github.io
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add latest.pdf
          git commit -m "Add latest.pdf"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
