name: Update Resume PDF

on:
  repository_dispatch:
    types: [pdf_update]

jobs:
  update_pdf:
    runs-on: ubuntu-latest

    steps:
      # - name: Clone the repository
      #   run: |
      #     git clone https://github.com/gavintranquilino/gavintranquilino.github.io.git/
      #     cd gavintranquilino.github.io
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     pwd .
          
      - name: Download PDF
        run: |
          curl -o resume.pdf https://raw.githubusercontent.com/gavintranquilino/gavins-resume/main/out/Gavin_Tranquilino.pdf
          ls -la

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update resume.pdf"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
